name: mtn_momo
version: 1.0.1
description: MTN MoMo SDK API client
homepage: http://fromtheinternet.co.za

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: '>=0.11.1 <0.13.0'

dev_dependencies:
  test: ^1.3.0
